version: "3.9"

services:
  database-test:
    container_name: postgres-test
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  hoverfly-test:
    container_name: hoverfly-test
    image: spectolabs/hoverfly:latest
    command:
      - "-webserver"
    volumes:
      - "./hoverfly:/hoverfly_app:ro"
    ports:
      - "8501:8500"
      - "8889:8888"
